# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main text color
theme[main_fg]="#D8DEE9"

# Title color for boxes
theme[title]="#ECEFF4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#FDB674"

# Background color of selected item in processes box
theme[selected_bg]="#3B4252"

# Foreground color of selected item in processes box
theme[selected_fg]="#ECEFF4"

# Color of inactive/disabled text
theme[inactive_fg]="#4C566A"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#5E81AC"

# Cpu box outline color
theme[cpu_box]="#4C566A"

# Memory/disks box outline color
theme[mem_box]="#4C566A"

# Net up/down box outline color
theme[net_box]="#4C566A"

# Processes box outline color
theme[proc_box]="#88C0D0"

# Box divider line and small boxes line color
theme[div_line]="#4C566A"

# Temperature graph colors
theme[temp_start]="#A3BE8C"
theme[temp_mid]="#8FBCBB"
theme[temp_end]="#BF616A"

# CPU graph colors
theme[cpu_start]="#81A1C1"
theme[cpu_mid]="#88C0D0"
theme[cpu_end]="#BF616A"

# Mem/Disk free meter
theme[free_start]="#A3BE8C"
theme[free_mid]=""
theme[free_end]=""

# Mem/Disk cached meter
theme[cached_start]="#EBCB8B"
theme[cached_mid]=""
theme[cached_end]=""

# Mem/Disk available meter
theme[available_start]="#FDB674"
theme[available_mid]=""
theme[available_end]=""

# Mem/Disk used meter
theme[used_start]="#BF616A"
theme[used_mid]=""
theme[used_end]=""

# Download graph colors
theme[download_start]="#FDB674"
theme[download_mid]=""
theme[download_end]="#ECEFF4"

# Upload graph colors
theme[upload_start]="#81A1C1"
theme[upload_mid]=""
theme[upload_end]="#ECEFF4"
